name: CI-CodeBuild 🚀

on:
  workflow_dispatch:

jobs:
  job1:
  
    runs-on:
      - codebuild-gha-secuirty-fix-test-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
    environment: prod
    steps:
      - name: test command
        run: echo "HELLO WORLD"
